train.x.bin$Continent_NASIA <- NULL
install.packages("polycor")
library(polycor)
het.mat <- hetcor(train.x.bin)$cor
fa.1 <- factanal(covmat=het.mat, factors=4, rotation="varimax")
install.packages("psych")
library(psych)
fa.2 <- fa(r=het.mat, nfactors=3, n.obs=nrow(train.x.bin), rotate="varimax")
# density plots and boxplots for outlier detection
par(mfrow=c(4,3))
plot(density(train.x$InMotif_1))
plot(density(train.x$InMotif_2))
plot(density(train.x$InMotif_3))
plot(density(train.x$ExMotif_1))
plot(density(train.x$ExMotif_2))
plot(density(train.x$ExMotif_3))
plot(density(train.x$SelfEff_1))
plot(density(train.x$SelfEff_2))
plot(density(train.x$SelfEff_3))
plot(density(train.x$Teacher_1))
plot(density(train.x$Teacher_2))
plot(density(train.x$Teacher_3))
par(mfrow=c(1,1))
par(mfrow=c(4,3))
boxplot(train.x$InMotif_1)
boxplot(train.x$InMotif_2)
boxplot(train.x$InMotif_3)
boxplot(train.x$ExMotif_1)
boxplot(train.x$ExMotif_2)
boxplot(train.x$ExMotif_3)
boxplot(train.x$SelfEff_1)
boxplot(train.x$SelfEff_2)
boxplot(train.x$SelfEff_3)
boxplot(train.x$Teacher_1)
boxplot(train.x$Teacher_2)
boxplot(train.x$Teacher_3)
par(mfrow=c(1,1))
# quantify through logistic regression
model <- glm(FlagAIB~., data=train, family="binomial")
plot(model)
# car package to calculate cookdistance
if(!require(car)) install.packages("car")
library(car)
cd <- cooks.distance(model, infl=influence(model, do.coef=TRUE))
